export const PROPOSAL_STAGES = {
  ENTRY: 'entry',
  PROFILE: 'profile',
  FAVORITES: 'favorites',
  REVEAL: 'reveal',
  FIRSTMEET: 'firstmeet',
  TIMELINE: 'timeline',
  REASONS: 'reasons',
  SKY: 'sky',
  LETTERS: 'letters',
  PROPOSAL: 'proposal',
  CELEBRATION: 'celebration'
};

export const STAGE_ORDER = [
  PROPOSAL_STAGES.ENTRY,
  PROPOSAL_STAGES.PROFILE,
  PROPOSAL_STAGES.FAVORITES,
  PROPOSAL_STAGES.REVEAL,
  PROPOSAL_STAGES.FIRSTMEET,
  PROPOSAL_STAGES.TIMELINE,
  PROPOSAL_STAGES.REASONS,
  PROPOSAL_STAGES.LETTERS,
  PROPOSAL_STAGES.SKY,
  PROPOSAL_STAGES.PROPOSAL,
  PROPOSAL_STAGES.CELEBRATION
];
